table Fact_Sales
	lineageTag: 5a75fdf4-dfd7-4bf2-877a-ab1ea379b10c

	measure 'Total Sales' =
			
			SUM(Fact_Sales[sales_amount])
		lineageTag: 3d2e9e72-e4f4-486e-ad7f-b271a2636fb4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales MoM Growth %' =
			
			VAR CurrentSales =
			    [Total Sales]
			VAR PreviousSales =
			    CALCULATE(
			        [Total Sales],
			        DATEADD(Dim_Date[date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(
			        CurrentSales - PreviousSales,
			        PreviousSales
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1dbea202-f875-4234-8ab1-493004545a9f

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: eaf8350e-d551-43e1-af37-0cb5f84a8ac7
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 00787f3e-65d8-4bcf-a55b-84718c95e449
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 7beb1b4c-4851-4bca-8734-7b2376152c17
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 25abbe33-6f4f-4f91-869f-2253333a9f22
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 06f2e825-94c0-4598-8392-b3b736592a19
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: aa9422bd-0213-429c-ba8e-4c2cc3bb9c21
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: bfef67c5-0b34-4d10-986c-02458736bf73
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 8d752fb9-a91e-4555-b829-3a075dcf93bf
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: ce8c837e-9e3a-4cf5-ae67-5f7b60a8dee5
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\sem 5\Bussiness  Intelligence\MiniProject\BrewMetrics\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

